version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - toshimaru
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
