language: objective-c
os:
  - osx
rvm:
  - 2.3.7
script:
  - bundle exec serverkit apply serverkit.yml.erb --variables=serverkit-variables.yml
  # just check, ignore exit status
  - bundle exec serverkit check serverkit.yml.erb --variables=serverkit-variables.yml || exit 0
